### PR TITLE
Api added

### LINKED ISSUE #16: [SIN] Using Flask and Python create a api to pull this repository's hacktoberfest statistics
Create a script that will store the no of pr's,issues generated during hacktober fest on this repo in a csv file and then create a API that anyone can call to fetch that csv file.

### PR DESCRIPTION
**Pull request by RitikMody**
I have completed the api, please review it @Pac23 @thewires2 .There are two endpoints : /prs and /issues.Csv files are also generated in the same folder.

### CODE REVIEW

**Comment by RitikMody** [comment]
please review this @Pac23 @darshmgandhi @AjayKhalsa @narenkhatwani @thewires2

**Comment by mm-git01** [comment]
> please review this @Pac23 @darshmgandhi @AjayKhalsa @narenkhatwani @thewires2

Code looks good,you need to add comments though. Also kindly deploy this on free heroku dyno or pythonanywhere or something similar and share acess so that we can pull the data at the end of hacktoberfest.

**Comment by RitikMody** [comment]
@Pac23 Yes sure , can you guys give me your heroku details so I can transfer the app to you'll .
And please label this pr hacktoberfest-accepted label or accept it.

**Comment by RitikMody** [comment]
@Pac23 @thewires2 
I've added comments and deployed it.
The endpoints are :
https://cmpn-codecell-hacktoberfest.herokuapp.com/issues
https://cmpn-codecell-hacktoberfest.herokuapp.com/prs

**Comment by thewires2** [comment]
Thank you for contribution @RitikMody , excellent work

**Comment by RitikMody** [comment]
Thank you for letting me work on this issue , enjoyed it. @thewires2

**Pull request merged**
