### PR TITLE
Added a sorting algorithm. Counting Sort.

### PR DESCRIPTION
**Pull request by darshmgandhi**
This is from Issue #14.

### CODE REVIEW

**Review by thewires2 — APPROVED** [review]

**Review by AjayKhalsa — CHANGES_REQUESTED** [review]
@darshmgandhi  Please add the code file in the Algorithm->Sorting folder

**Comment by darshmgandhi** [comment]
@AjayKhalsa  the change has been made.

**Comment by AjayKhalsa** [comment]
Thanks for your contribution @darshmgandhi

**Comment by darshmgandhi** [comment]
Thanks for the review @AjayKhalsa

**Pull request merged**
